<?php

namespace App\Form;

use App\Entity\Company;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CompanyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, array(
            	'label' => 'Nom de la société',
	            'attr' => array(
	            	'placeholder' => 'Nom de la société'
	            )
            ))
            ->remove('lastName')
	        ->remove('firstName')
	        ->remove('cin')
	        ->remove('nationality')
	        ->remove('qualification')
	        ->remove('employee')
	        ->remove('grade')
	        ->remove('birthday')
        ;
    }

    public function getParent() {
	    return ArtisanType::class; // TODO: Change the autogenerated stub
    }

	public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Company::class,
        ]);
    }
}
